# Generated by Django 3.2 on 2021-07-03 16:53

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('comment_id', 'post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('post_id', 'user')},
        ),
        migrations.RemoveField(
            model_name='post',
            name='assets',
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=blog.models.upload_to)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
            options={
                'unique_together': {('id', 'post_id')},
            },
        ),
    ]
