# Generated by Django 3.2.5 on 2021-07-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210725_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='downvotes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upvotes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
