# Generated by Django 3.2.5 on 2021-08-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210801_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='is_liked',
            new_name='is_upvoted',
        ),
    ]
