# Generated by Django 3.2.5 on 2021-08-22 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210821_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_replied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment'),
        ),
    ]
